In [1]:
import numpy as np
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
'''Extract the diagonal without using numpy.diagonal
diagonal is elements are those where row index =column index '''
rows = np.array([0, 1, 2, 3, 4])
cols = np.array([0, 1, 2, 3, 4])
diagonal = x[rows, cols]
print(diagonal)

'''or we can do:
idx = np.arange(5)
diagonal = x[idx, idx]'''

[ 0  6 12 18 24]


In [4]:
# extraxting all elements greater than 10 using boolean extracting 
result = x[x > 10]
print(result)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [5]:
rev_rows = x[:, ::-1]
print(rev_rows)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]
